REDIS_PASSWORD=immortal_redis_secret_password
REDIS_HOST=judge0-redis

POSTGRES_HOST=judge0-db
POSTGRES_USER=judge0
POSTGRES_DB=judge0
POSTGRES_PASSWORD=immortal_pg_secret_password

AUTHN_TOKEN=
AUTHN_HEADER=X-Auth-Token

AUTHZ_TOKEN=
AUTHZ_HEADER=X-Auth-User
